name: GuardianSkyWars
version: ${project.version}
main: dev.mruniverse.guardianskywars.GuardianSkyWars
api-version: 1.16
depend: [ GuardianLIB ]
softdepend: [ PlaceholderAPI ]
authors: [ MrUniverse44, Sebastnchan ]
description: SkyWars plugin created by Darkness Development
website: rigox.club
commands:
  gsw:
    description: Plugin Main Command.
  guardianskywars:
    description: Plugin Main Command.